### PR TITLE
Update case study grades

### LINKED ISSUE #93: Update case study grades UI
update the ui where necessary i.e where case study creation occurs and the progress page. user should be able to input grade totals for each dashboard section.

### LINKED ISSUE #94: update case study grades backend and database.
Update this to match the new UI

### PR DESCRIPTION
**Pull request by muizzyusuf**
updated migrations
updated case study creation and editing 
updated case study controller (store & update)
updated all teacher comment sections in each dashboard section to reflect the total for each section
updated progress page to show the total for each section

### CODE REVIEW

**Comment by mogden8** [comment]
Great work muizz

**Comment by DekaAbdi** [comment]
Ok, comment on this for gitstats

**Comment by Radhi1017** [comment]
awesome work !

**Comment by DekaAbdi** [comment]
Splendid!

**Review by mogden8 — APPROVED** [review]
Wow! Cool!

**Review by Radhi1017 — APPROVED** [review]
awesome !

**Pull request merged**
